modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"

description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="[6.0.8,6.1.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cofh_core"
    mandatory=true
    versionRange="[11.0.0,12.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="thermal"
    mandatory=true
    versionRange="[11.0.0,12.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jei"
    mandatory=false
    versionRange="[15,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="createaddition"
    mandatory=true
    versionRange="[1.2.0,)"
    ordering="AFTER"
    side="BOTH"
